# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Basic site settings ###################################################

title: Victor Pozzobon
email: victor.pozzobon@yahoo.fr
author: Victor Pozzobon
last_update: September 2024
description: >- # this means ignore newlines
  Victor Pozzobon is a habilitated Ph.D. leading research in biotechnology. Microalgae are his favorite microorganisms because of their photosynthetic ability. He deploys all kinds of numerical tools to investigate cell growth, viability, and secondary metabolites production. 

baseurl: ""
url: "victorpozzobon.github.io"

# Jekyll settings #######################################################

# this tells jekyll to include the content of the _pages
# folder when generating the static site
include:
  - _pages

# options for SASS (compiled CSS)
sass:
  # source folder
  sass_dir: _sass
  # when compiling, minimize size
  style: compressed

### ! these cannot be changed for Github pages ! ###

# index for related posts
lsi: false
# disable custom plugins
safe: true
# markdown conversion
markdown: kramdown
# highlighting for text and code
highlighter: rouge
# build only pages that changed
incremental: false

### ! these can be changed ! ###

# show excerpts from posts on the news page
show_excerpts: true

# Jekyll plugins go here
plugins:
  # generate a <head> tag for SEO automatically
  - jekyll-seo-tag
  # generates an rss feed from posts and news
  - jekyll-feed
  
# Custom settings #######################################################

# social/analytics variables
logo: "/assets/images/me.jpg"
linkedin_username: victor-pozzobon-95b9529a
github_username:  victorpozzobon
google_scholar: XOAdaN4AAAAJ
orc_id: 0000-0003-1530-0834
rg_id: Victor_Pozzobon

# Nav
navigation:
  - item: "About"
    link: "/about/"
  - item: "Research"
    link: "/academic/"
  #- item: "CV(s)"
    #link: "/resume/"
  - item: "Numerics"
    link: "/numerics/"
  - item: "Biotechnology"
    link: "/biotech/"
  - item: "OpenFOAM"
    link: "/openfoam/"
  - item: "Dissemination"
    link: "/dissemination/"
